// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD7A8Z1_KR9xns-v9_-MBzMcNv7E4jigmw',
    appId: '1:324511552179:web:8775e5d81403f03599d6c6',
    messagingSenderId: '324511552179',
    projectId: 'dochelp-8b635',
    authDomain: 'dochelp-8b635.firebaseapp.com',
    storageBucket: 'dochelp-8b635.appspot.com',
    measurementId: 'G-TKLPQM9DN5',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAsMqKz7JXzQETGMRu1VZ3cVtiFpaMD7w4',
    appId: '1:324511552179:android:a251a0f4572abd6599d6c6',
    messagingSenderId: '324511552179',
    projectId: 'dochelp-8b635',
    storageBucket: 'dochelp-8b635.appspot.com',
  );

}